---
- name: Prep the nodes
  include_tasks: prep.yaml
  tags:
    - prep

- name: Backup overcloud DB
  include_tasks: overcloud_db_backup.yaml
  tags:
    - overcloud_db

- name: Backup overcloud FS
  include_tasks: overcloud_filesystem_backup.yaml
  tags:
    - overcloud_fs

- name: Configure Rear backup
  include_tasks: overcloud_rear_backup.yaml
  tags:
    - rear_backup
