---
- name: Create directory to backup overcloud DB
  file:
    path: "{{ nfs.dst }}/overcloud_DB"
    state: directory
    mode: "775"
  when: ansible_hostname == primary_controller
  tags:
    - overcloud_db

- name: Fetch mysql root password
  command:
    cmd: "/bin/hiera -c /etc/puppet/hiera.yaml mysql::server::root_password"
  register: mysql_root_password_cmd_output
  when: ansible_hostname == primary_controller
  tags:
    - overcloud_db

- name: Convert the database root password if unknown
  set_fact:
    mysql_root_password: "{{ mysql_root_password_cmd_output.stdout_lines[0] }}"
  when: ansible_hostname == primary_controller
  tags:
    - overcloud_db

- name: Create MySQL backup script
  template:
    src: backup_mysql.sh.j2
    dest: "{{ nfs.dst }}/overcloud_DB/backup_mysql.sh"
    mode: u+rwx
  when: ansible_hostname == primary_controller
  tags:
    - overcloud_db

- name: Run the MySQL backup script
  command: "{{ nfs.dst }}/overcloud_DB/backup_mysql.sh"
  when: ansible_hostname == primary_controller
  tags:
    - overcloud_db

- name: Archive the OpenStack databases
  shell: |
    /bin/tar --ignore-failed-read --xattrs \
      -zcf {{ nfs.dst }}/overcloud_DB/openstack-overcloud-backup-mysql-{{ hostvars[inventory_hostname]['ansible_date_time']['iso8601_basic_short'] }}.tar \
      {{ nfs.dst }}/overcloud_DB/*.sql
  when: ansible_hostname == primary_controller
  tags:
    - overcloud_db

- name: Remove temp files
  file:
    name: "{{ item }}"
    state: absent
  when: ansible_hostname == primary_controller
  loop:
    - "{{ nfs.dst }}/overcloud_DB/backup_mysql.sh"
    - "{{ nfs.dst }}/overcloud_DB/openstack-backup-mysql-grants.sql"
    - "{{ nfs.dst }}/overcloud_DB/openstack-backup-mysql.sql"
  tags:
    - overcloud_db


