---
- name: Create NFS directory
  file:
    path: "{{ nfs.dst }}"
    state: directory
    mode: "775"
  tags:
    - prep

- name: Mount NFS share
  mount:
    path: "{{ nfs.dst }}"
    state: "mounted"
    fstype: "nfs"
    src: "{{ nfs.share }}"
  tags:
    - prep

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ packages }}"
  tags:
    - prep
    - rear_backup

- name: Disable stonith
  shell: "pcs property set stonith-enabled=false"
  when: ansible_hostname == primary_controller
  register: disable_stonith
  any_errors_fatal: true
  tags:
    - prep
    - rear_backup

- name: Disable prep
  set_fact:
    disable_prep: true
  tags:
    - prep
    - rear_backup
