- name: Set cluster offline
  pacemaker_cluster:
    state: offline
    node: all

- name: List all containers
  command:
    cmd: "docker ps -q"
  register: docker_ps

- name: Stop all containers
  docker_container:
    name: "{{ item }}"
    state: stopped
  loop:
    - "{{ docker_ps.stdout_lines }}"

- name: Create rear config file
  template:
    src: rear_config.j2
    dest: "/etc/rear/local.conf"
    mode: u+rwx

- name: Execute rear to backup
  command:
    cmd: "rear -d -v mkbackup"
  register: rear_execution

- name: rear backup output
  debug:
    msg: "{{ rear_execution.stdout }}"


