---
- name: Create NFS directory
  file:
    path: "{{ nfs.dst }}"
    state: directory
    mode: "775"

- name: Mount NFS share
  mount:
    path: "{{ nfs.dst }}"
    state: "mounted"
    src: "{{ nfs.share }}"

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ packages }}"