---
- name: Create NFS directory
  file:
    path: "{{ nfs.dst }}"
    state: directory
    mode: "775"
  tags:
    - prep

- name: Mount NFS share
  mount:
    path: "{{ nfs.dst }}"
    state: "mounted"
    fstype: "nfs"
    src: "{{ nfs.share }}"
  tags:
    - prep

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ packages }}"
  tags:
    - prep
